-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 12:08:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `DAM` DEFAULT CHARACTER SET utf8 ;
USE `DAM` ;

-- -----------------------------------------------------
-- Table `DAM`.`Electrovalvulas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DAM`.`Electrovalvulas` ;

CREATE TABLE IF NOT EXISTS `DAM`.`Electrovalvulas` (
  `electrovalvulaId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`electrovalvulaId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DAM`.`Dispositivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DAM`.`Dispositivos` ;

CREATE TABLE IF NOT EXISTS `DAM`.`Dispositivos` (
  `dispositivoId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `ubicacion` VARCHAR(200) NULL,
  `electrovalvulaId` INT NOT NULL,
  PRIMARY KEY (`dispositivoId`, `electrovalvulaId`),
  INDEX `fk_Dispositivos_Electrovalvulas1_idx` (`electrovalvulaId` ASC) ,
  CONSTRAINT `fk_Dispositivos_Electrovalvulas1`
    FOREIGN KEY (`electrovalvulaId`)
    REFERENCES `DAM`.`Electrovalvulas` (`electrovalvulaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAM`.`Mediciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DAM`.`Mediciones` ;

CREATE TABLE IF NOT EXISTS `DAM`.`Mediciones` (
  `medicionId` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `valor` VARCHAR(100) NULL,
  `dispositivoId` INT NOT NULL,
  PRIMARY KEY (`medicionId`, `dispositivoId`),
  INDEX `fk_Mediciones_Dispositivos_idx` (`dispositivoId` ASC) ,
  CONSTRAINT `fk_Mediciones_Dispositivos`
    FOREIGN KEY (`dispositivoId`)
    REFERENCES `DAM`.`Dispositivos` (`dispositivoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DAM`.`Log_Riegos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DAM`.`Log_Riegos` ;
CREATE TABLE IF NOT EXISTS `DAM`.`Log_Riegos` (
  `logRiegoId` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `apertura` INT NOT NULL,
  `electrovalvulaId` INT NOT NULL,
  PRIMARY KEY (`logRiegoId`, `electrovalvulaId`),
  INDEX `fk_Log_Riegos_Electrovalvulas_idx` (`electrovalvulaId` ASC) ,
  CONSTRAINT `fk_Log_Riegos_Electrovalvulas`
    FOREIGN KEY (`electrovalvulaId`)
    REFERENCES `DAM`.`Electrovalvulas` (`electrovalvulaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into Electrovalvulas (nombre) values ("valvula 1");
insert into Electrovalvulas (nombre) values ("valvula 2");
insert into Electrovalvulas (nombre) values ("valvula 3");
insert into Electrovalvulas (nombre) values ("valvula 4");
insert into Dispositivos (nombre, ubicacion, electrovalvulaId) values ("Disp 1", "cocina", 1);
insert into Dispositivos (nombre, ubicacion, electrovalvulaId) values ("Disp 2", "banio", 2);
insert into Dispositivos (nombre, ubicacion, electrovalvulaId) values ("Disp 3", "jardin", 4);
insert into Dispositivos (nombre, ubicacion, electrovalvulaId) values ("Disp 4", "dormitorio", 3);

insert into Mediciones (fecha, valor, dispositivoId) values (now(), "11", 1);
insert into Mediciones (fecha, valor, dispositivoId) values (now(), "22", 2);
insert into Mediciones (fecha, valor, dispositivoId) values (now(), "33", 3);
insert into Mediciones (fecha, valor, dispositivoId) values (now(), "44", 4);

insert into Mediciones (fecha, valor, dispositivoId) values (now() + INTERVAL 10 SECOND, "12", 1);
insert into Mediciones (fecha, valor, dispositivoId) values (now() + INTERVAL 10 SECOND, "23", 2);
insert into Mediciones (fecha, valor, dispositivoId) values (now() + INTERVAL 10 SECOND, "34", 3);
insert into Mediciones (fecha, valor, dispositivoId) values (now() + INTERVAL 10 SECOND, "45", 4);

insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(1,now(),1);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(0,now() + INTERVAL 10 SECOND,1);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(1,now() + INTERVAL 20 SECOND,1);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(0,now(),2);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(1,now() + INTERVAL 10 SECOND,2);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(0,now() + INTERVAL 20 SECOND,2);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(1,now(),3);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(0,now() + INTERVAL 10 SECOND,3);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(1,now() + INTERVAL 20 SECOND,3);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(0,now(),4);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(1,now() + INTERVAL 10 SECOND,4);
insert into Log_Riegos(apertura,fecha,electrovalvulaId) values(0,now() + INTERVAL 20 SECOND,4);




